# generated by datamodel-codegen:
#   filename:  telemetry.json
#   timestamp: 2025-12-10T23:23:13+00:00

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Optional


class Type(Enum):
    GLOBAL_POSITION_INT = 'GLOBAL_POSITION_INT'
    ATTITUDE = 'ATTITUDE'
    BATTERY_STATUS = 'BATTERY_STATUS'
    HEARTBEAT = 'HEARTBEAT'


@dataclass
class DroneTelemetry:
    type: Type
    timestamp: Optional[float] = None
    lat: Optional[float] = None
    lon: Optional[float] = None
    alt: Optional[float] = None
    relative_alt: Optional[float] = None
    vx: Optional[float] = None
    vy: Optional[float] = None
    vz: Optional[float] = None
    hdg: Optional[float] = None
    roll: Optional[float] = None
    pitch: Optional[float] = None
    yaw: Optional[float] = None
    voltage: Optional[float] = None
    remaining: Optional[float] = None
    armed: Optional[bool] = None
    mode: Optional[str] = None
    system_status: Optional[int] = None
